### ISSUE TITLE
Problem with middleware

### ISSUE THREAD

**Issue by SaphiLC** [adbario/slim-secure-session-middleware#14]
Im unable to access session variables inside middleware... they are available in the controllers tho, no idea why. Any ideas or suggestions?

**Comment by adbario** [comment]
Post an example how you initialize and use the sessions.

Slim executes middlewares on reverse order, so in your code where you add the middlewares, **session middleware should be last, after all other middleware that uses sessions**.

**Comment by doktor1360** [comment]
Please excuse me for briefly reopening this for a moment, I've been struggling with this session persistence stuff and I'm just addled because I don't understand the load order - or middleware execution. By reverse order, that throws me... I just simply can't seem to get this working properly, and I know it's not the code to your middleware. Nearly every example I've seen is using a closure of sorts, but this is about as close I've come to my situation where I'm using a class method closures for routing control. I know this is vague, but what I was really looking for is some sort of understanding of the whole middleware loading sequence. I don't know what/where to get any assistance working thru this issue, and didn't know if it was proper to do that here or not... thanx in advance!

**Comment by adbario** [comment]
Slim documentation is the best source to find out how middleware works in Slim 3: http://www.slimframework.com/docs/v3/concepts/middleware.html

> The last middleware layer added is the first to be executed.

When you implement middleware in your code, they need to be added in reverse order.
```php
$subject->add( new ThisDependsOnMiddlewareOne() );
$subject->add( new MiddlewareOne() );
```

Session middleware should be added before any other middleware, as they might use sessions. And when we reverse this, it means that session middleware should be the last middleware added in your code.

**Comment by doktor1360** [comment]
Stellar... thx @adbario (Riku) - that's kind of what I was thinking. It'll make any debugging and/or profiling a lot easier to understand when I know what I'm seeing in the debugger dumps...

Again, thanx so much for your time - it is greatly appreciated!

FWIW, your code base ROCKS - well written, easily understood with coverage for all that's needed and then some!
